name: Build and Push to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    #checkout
    - name: Checkout code
      uses: actions/checkout@v4
    
    #Set up QEMU
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    #Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    #login to GHCR
    - name: login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    #extract metadata
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/cups-lj2400l:latest
        tags: |
          type=sha
          type=ref, event=branch
          type=semver, pattern=v{{version}}
      
    #Build and push Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name == 'push' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: |
          org.opencontainers.image.source=${{ github.repository }}
          org.opencontainers.image.description=CUPS printer with Lenovo LJ2400L driver
          org.opencontainers.image.licenses=MIT


        
